# Generated by Django 5.2.2 on 2025-06-07 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mikrotik',
            fields=[
                ('Mikid', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('MikUsername', models.CharField(max_length=50)),
                ('MikPassword', models.CharField(max_length=100)),
                ('MikName', models.CharField(max_length=50)),
                ('MikIp', models.CharField(max_length=15)),
                ('MikPort', models.PositiveIntegerField()),
                ('MikCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
