# Generated by Django 5.2.2 on 2025-06-07 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('upass', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('upload', models.IntegerField()),
                ('download', models.IntegerField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('Hotspot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mikrotik.mikrotik')),
            ],
        ),
    ]
