# Generated by Django 5.2.2 on 2025-06-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0002_hotspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotik',
            name='Mikid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
