# Generated by Django 5.2.2 on 2025-06-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0003_alter_mikrotik_mikid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='download',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='speed',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='upload',
            field=models.CharField(max_length=10),
        ),
    ]
